[package]
name = "tet-ris"
version = "0.2.3"
edition = "2021"
description = "A play a quick game of 1984-ish Tetris right in the terminal!"
readme = "README.md"
repository = "https://github.com/manorajesh/tet-ris"
license = "MIT"
license-file = "LICENSE"
keywords = ["tetris", "game", "terminal"]
categories = ["games"]
exclude = [".vscode", "images", ".github"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "^0.26.1"
rand = "^0.8.5"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = 1