on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: MacOS x86_64 build

jobs:
  apple-darwin-x86_64:
    name: MacOS x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-apple-darwin