on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: Windows AArch64 build

jobs:
  windows-x86_64-msvc:
    name: Windows AArch64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-pc-windows-msvc
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-pc-windows-msvc